rule all: 
    input: 
        #"results/importqza/emp-paired-end-sequences.qza",
        #"results/demultiplex/demux-full.qza",
        #demuxsub = "results/subsamples/demux-subsample.qza",
        #demuxsumm = "results/subsamples/demux-subsample.qzv",
        "results/demux-subsample/per-sample-fastq-counts.tsv",


include: "rules/emppaired.smk"
include: "rules/demux.smk"
include: "rules/subsamples.smk"
include: "rules/filter_samples.smk"
