rule all: 
    input: 
        #"results/importqza/emp-paired-end-sequences.qza",
        #"results/demultiplex/demux-full.qza",
        #demuxsub = "results/subsamples/demux-subsample.qza",
        #demuxsumm = "results/subsamples/demux-subsample.qzv",
        "results/demux-subsample/per-sample-fastq-counts.tsv",
        "results/demux-subsample/demux.qza",
        "results/denoising-stats.qza",
        "results/summarized/table.qzv",
        "results/summarized/rep-seqs.qzv",
        "results/summarized/denoising-stats.qzv",


include: "rules/emppaired.smk"
include: "rules/demux.smk"
include: "rules/subsamples.smk"
include: "rules/filter_samples.smk"
include: "rules/denoise_paired.smk"
include: "rules/all_summarized.smk"
